### ISSUE TITLE
CS AR OD HP may be formatted to 1 decimal place.

### ISSUE THREAD

**Issue by ufolyah** [MikiraSora/OsuLiveStatusPanel#6]
It seems like you parse all float numbers to 2 decimal places when output to file.

**Comment by MikiraSora** [comment]
Considering that some parameters (for expamle AR10.03) represent two decimal places, I set the value of other floating-point parameters to keep two decimal places by default.
And It's hard to customize special param which user want because of implement.
But this project will be rewrite as new project in next generation of Sync named EmberTools.
